services:
  - type: web
    name: neyroscenebot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: REPLICATE_API_TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false